# =============================================
# Build config
# =============================================

root:             _gh_pages
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets

# Data
data:             data/*.{json,yml}

# Templates
templates:        templates
includes:         <%= site.templates %>/includes/*.hbs
layouts:          <%= site.templates %>/layouts
layout:           default.hbs

# Extensions
helpers:          
  - <%= site.templates %>/helpers/*.js
  - handlebars-helper-br

plugins:
  - assemble-contrib-anchors
  - assemble-contrib-wordcount
  - assemble-contrib-toc

# Theme
theme:            theme
components:       <%= site.theme %>/components


# =============================================
# Project metadata
# =============================================

# Assemble metadata.
assemble:
  latest:         <%= pkg.version %>

# GitHub
username:         mroberts46
name:             <%= pkg.name %>
download:
  source:         <%= pkg.homepage %>/archive/master.zip


# =============================================
# Site metadata
# =============================================

brand:            Phantom Development
title:            PHANTOM DEVELOPMENT
lead:             A virtual playground for an aspiring front-end developer.

version:          <%= pkg.version %>
description:      <%= pkg.description %>
license:
  type:           <%= pkg.licenses[0].type %>
  url:            <%= pkg.licenses[0].url %>


# Links
url:
  repo:           <%= pkg.homepage %>
  bugs:           <%= pkg.bugs.url %>?state=open
  ghpages:        https://<%= site.username %>.github.io/<%= pkg.name %>/

  # Site
  domain:         http://Phantom-Development.github.io
  about:          <%= site.url.domain %>/about/
  blog:           <%= site.url.domain %>/blog/
  resume:         <%= site.url.domain %>/resume/
  gallery:        <%= site.url.domain %>/gallery/
  contact:        <%= site.url.domain %>/contact/


# SEO/SEM
ga:
  id:             false
  domain:         assemble.github.io
  siteid:         false
  # Google Tags (see: https://www.google.com/tagmanager/)
  tags:           false

# Comments
disqus:
  enabled:        true
  shortname:      <%= pkg.name %>

# Social
social:
  twitter:
    via:          mindlessgent
    username:     mindlessgent
  facebook:       true
  linkedin:       true
  gplus:          true
  hn:             false
  google:         false

# Sharing
sharing:
  twitter:        false
  facebook:       false
  gplus:          false
  hn:             false
  google:         false